# Generated by Django 3.2.5 on 2021-07-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210725_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
