# Generated by Django 3.2.5 on 2021-08-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_item_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
